#!/usr/bin/env python3
"""Split combined Obsidian documentation into individual .md files.

Reads a markdown blob separated by `---` horizontal rules (as generated by
the architecture doc workflow) and emits one file per section. Filenames are
derived from the `## File: [Name]` header inside each section.

Usage:
    python3 split_obsidian_docs.py combined_output.md -o /path/to/vault
"""

import argparse
import os
import re
import sys
from pathlib import Path


def _sanitize_filename(name: str) -> str:
    name = name.strip()
    # Collapse filesystem-dangerous characters
    safe = re.sub(r'[\\/:*?"<>|]', '_', name)
    if not safe:
        safe = 'untitled'
    if not safe.endswith('.md'):
        safe += '.md'
    return safe


def _extract_filename(section: str) -> str:
    m = re.search(r'^## File:\s*(.+)$', section, re.MULTILINE)
    if m:
        return _sanitize_filename(m.group(1).strip())
    return 'untitled.md'


def split_markdown(input_path: str, output_dir: str):
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    with open(input_path, 'r', encoding='utf-8') as fh:
        content = fh.read()

    # Split on lines that are exactly --- (horizontal rule between sections)
    sections = re.split(r'\n\s*---\s*\n', content)

    written = []
    for section in sections:
        section = section.strip()
        if not section:
            continue

        filename = _extract_filename(section)
        dest = out / filename

        # Handle collisions by appending a counter
        counter = 1
        stem = Path(filename).stem
        while dest.exists():
            dest = out / f'{stem}_{counter}.md'
            counter += 1

        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(section)
            fh.write('\n')
        written.append(dest.name)

    print(f'Wrote {len(written)} files to {out}:')
    for w in written:
        print(f'  - {w}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Split combined markdown into individual Obsidian .md files'
    )
    parser.add_argument('input', help='Path to the combined markdown file')
    parser.add_argument(
        '--output-dir', '-o',
        default='./obsidian_vault',
        help='Directory to write individual .md files (default: ./obsidian_vault)'
    )
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f'Error: {args.input} not found', file=sys.stderr)
        sys.exit(1)

    split_markdown(args.input, args.output_dir)
