#!/usr/bin/env python3
"""
beaverhead_inmate.py
=====================
Fetches Beaverhead County (MT) jail roster PDF from
https://beaverheadcountymt.gov/departments/sheriff/jail-roster/
and parses it into JailBookingRecords.

The page is a WordPress attachment wrapper that embeds the current roster PDF
at /wp-content/uploads/YYYY/MM/Jail-Roster.pdf.  We download the PDF and
parse it with pdfplumber.
"""
from __future__ import annotations

import hashlib
import io
import logging
import re
from urllib.parse import urljoin

import pdfplumber
import requests

from services.ingestion.models import JailBookingRecord

logger = logging.getLogger(__name__)

BASE_PAGE = "https://beaverheadcountymt.gov/departments/sheriff/jail-roster/"
PDF_URL_PATTERN = re.compile(
    r"https://beaverheadcountymt\.gov/wp-content/uploads/\d{4}/\d{2}/Jail-Roster\.pdf",
    re.IGNORECASE,
)
SESSION = requests.Session()
SESSION.headers.update({
    "User-Agent": "Mozilla/5.0 (compatible; MontanaBlotter/1.0; +https://montanablotter.com)",
    "Accept": "text/html,application/xhtml+xml,application/pdf;q=0.9,*/*;q=0.8",
})


def _discover_pdf_url(session: requests.Session, page_url: str = BASE_PAGE) -> str | None:
    """Scrape the WordPress attachment page for the embedded PDF URL."""
    try:
        resp = session.get(page_url, timeout=30)
        resp.raise_for_status()
    except Exception as exc:
        logger.warning("Beaverhead roster page fetch failed: %s", exc)
        return None

    match = PDF_URL_PATTERN.search(resp.text)
    if match:
        url = match.group(0)
        logger.info("Beaverhead discovered roster PDF: %s", url)
        return url

    # Fallback: look for any /wp-content/uploads/.../Jail-Roster.pdf link
    fallback = re.search(
        r'href=[\'"]([^\'"]*wp-content/uploads/\d{4}/\d{2}/Jail-Roster\.pdf[^\'"]*)[\'"]',
        resp.text,
        re.IGNORECASE,
    )
    if fallback:
        url = fallback.group(1)
        logger.info("Beaverhead fallback roster PDF: %s", url)
        return url

    logger.warning("No Beaverhead roster PDF found on page")
    return None


def _download_pdf(session: requests.Session, url: str) -> bytes | None:
    try:
        resp = session.get(url, timeout=60, allow_redirects=True)
        resp.raise_for_status()
        if resp.content[:4] != b"%PDF":
            logger.warning("Beaverhead URL did not return a PDF (%d bytes)", len(resp.content))
            return None
        return resp.content
    except Exception as exc:
        logger.warning("Beaverhead PDF download failed: %s", exc)
        return None


def _parse_beaverhead_pdf(pdf_bytes: bytes, source_url: str) -> list[JailBookingRecord]:
    """Parse the Beaverhead County jail roster PDF into booking records.

    The PDF is an "Inmate Offense List, with Statute" generated by the sheriff's
    case management system.  Each inmate block starts with a header line::

        Book#: 26BK00095 Name: AMOS,NICHOLASC NameID: 21693 Rel.Dt: **/**/**

    followed by statute/charge rows.  The header line contains the booking
    number (Book#), the person name (Name: LAST,FIRSTMIDDLE), and a NameID.
    We extract one record per unique Book#.
    """
    try:
        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            text = "\n".join((page.extract_text() or "") for page in pdf.pages)
    except Exception as exc:
        logger.warning("Beaverhead PDF parse failed: %s", exc)
        return []

    if not text.strip():
        logger.info("Beaverhead PDF contained no extractable text")
        return []

    logger.info("Beaverhead PDF text length: %d chars", len(text))

    records: list[JailBookingRecord] = []
    seen_book_numbers: set[str] = set()

    # Header line: "Book#: 26BK00095 Name: AMOS,NICHOLASC NameID: 21693 ..."
    header_re = re.compile(
        r"Book#\s*:\s*([A-Z0-9-]+)\s+Name\s*:\s*([A-Z,]+)\s+NameID\s*:\s*(\d+)",
        re.IGNORECASE,
    )

    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue

        m = header_re.search(line)
        if not m:
            continue

        booking_number = m.group(1).strip()
        raw_name = m.group(2).strip()
        name_id = m.group(3).strip()

        if booking_number in seen_book_numbers:
            continue
        seen_book_numbers.add(booking_number)

        # Normalise name: "AMOS,NICHOLASC" → "Amos, Nicholas C"
        if "," in raw_name:
            last_part, first_part = raw_name.split(",", 1)
            last = last_part.strip().title()
            first = first_part.strip()
            # Split fused first+middle initial: NICHOLASC → NICHOLAS C
            if len(first) >= 4 and first[:-1].isalpha() and first[-1].isalpha():
                first = first[:-1].title() + " " + first[-1]
            else:
                first = first.title()
            person_name = f"{last}, {first}"
        else:
            person_name = raw_name.title()

        source_record_id = f"beaverhead:{booking_number.lower()}:{name_id}"
        records.append(JailBookingRecord(
            source_record_id=source_record_id,
            person_name=person_name,
            age=None,
            booking_number=booking_number,
            booking_at=None,
            charges_summary="Charge details available on the official Beaverhead County roster.",
            source_url=source_url,
        ))

    logger.info("Beaverhead roster: parsed %d records from %d unique book numbers",
                len(records), len(seen_book_numbers))
    return records


def fetch_beaverhead_bookings(source_url: str | None = None) -> list[JailBookingRecord]:
    """Fetch and parse the Beaverhead County jail roster.

    Discovers the current PDF URL from the WordPress page, downloads it,
    and parses the roster into booking records.
    """
    target_page = source_url or BASE_PAGE
    pdf_url = _discover_pdf_url(SESSION, target_page)
    if not pdf_url:
        return []

    pdf_bytes = _download_pdf(SESSION, pdf_url)
    if not pdf_bytes:
        return []

    return _parse_beaverhead_pdf(pdf_bytes, pdf_url)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    recs = fetch_beaverhead_bookings()
    print(f"Fetched {len(recs)} Beaverhead records")
    for r in recs[:5]:
        print(r)
